# Numpy

In [1]:
import numpy as np

In [2]:
myArr = np.array([2, 3, 32, 7], np.int8)

In [3]:
myArr

array([ 2,  3, 32,  7], dtype=int8)

# Array Creation: conversion from other python structures

In [4]:
listArray = np.array([[1, 2, 3], [5, 8, 5], [0, 3, 1]])

In [5]:
listArray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [6]:
np.array({34, 37, 37})

array({34, 37}, dtype=object)

In [7]:
zeroes = np.zeros((2, 5))

In [8]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
rng = np.arange(5)

In [10]:
rng

array([0, 1, 2, 3, 4])

In [11]:
lspace = np.linspace(1, 5, 12)

In [12]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [13]:
emp = np.empty((4, 6))

In [14]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86921279e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        6.89805151e-307, 1.78020169e-306, 1.42410974e-306]])

In [15]:
emp_like = np.empty_like(lspace)

In [16]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [17]:
ide = np.identity(15)

In [18]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [20]:
arr = np.arange(99)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [23]:
arr = arr.reshape(3, 33)

In [24]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [25]:
arr = arr.ravel()

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [28]:
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [29]:
ar = np.array(x)

In [30]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [31]:
ar.sum(axis=0)

array([12,  8,  9])

In [32]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [33]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [34]:
ar.flat

In [35]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [36]:
ar.ndim

2

In [37]:
ar.nbytes

36

In [38]:
one = np.array([1, 3, 4, 634, 2])

In [39]:
one.argmax()

3

In [40]:
one.argmin()

0

In [41]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [42]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [43]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [46]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [47]:
[324, 34] + [324, 34]

[324, 34, 324, 34]

In [48]:
ar * ar2 #Multiply according to the index

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [49]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [50]:
ar.sum()

29

In [51]:
ar.max()

7

In [52]:
ar.min()

0

In [53]:
np.where(ar > 5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [54]:
np.count_nonzero(ar)

8

In [56]:
np.nonzero(ar) # give axis = 0 && axis = 1 as 2 different array

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
import sys

In [59]:
py_ar = [0, 4, 56, 2]

In [60]:
np_ar = np.array(py_ar)

In [61]:
sys.getsizeof(1) * len(py_ar)  # Give size of py_ar

112

In [62]:
np_ar.itemsize * np_ar.size  # Give size of np_ar

16